adding config files to git

diff --git a/src/cscripts/env b/src/cscripts/env
--- a/src/cscripts/env
+++ b/src/cscripts/env
@@ -9,8 +9,8 @@
 CNODEBIN="${HOME}/.cabal/bin/cardano-node"             # Override automatic detection of cardano-node executable
 CCLI="${HOME}/.cabal/bin/cardano-cli"                  # Override automatic detection of cardano-cli executable
 #CNCLI="${HOME}/.cargo/bin/cncli"                       # Override automatic detection of executable (https://github.com/AndrewWestberg/cncli)
-CNODE_HOME="$HOME/projects/cardano/cardano-scripts/src/tconfig"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
-CNODE_EXEC_HOME="$HOME/projects/cardano/cardano-scripts/exec/state-node-shelly-mainnet/"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
+CNODE_HOME="$HOME/projects/cardano-scripts/src/tconfig"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
+CNODE_EXEC_HOME="$HOME/projects/cardano-scripts/exec/state-node-shelly-mainnet/"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
 CNODE_PORT=3001                                         # Set node port
 CONFIG="${CNODE_HOME}/mainnet-config.json"               # Override automatic detection of node config path
 SOCKET="${CNODE_EXEC_HOME}/node.socket"            # Override automatic detection of path to socket
@@ -38,7 +38,7 @@ USE_EKG="Y"                                            # Use EKG metrics from th
 #WALLET_FOLDER="${CNODE_HOME}/priv/wallet"              # Root folder for Wallets
 #POOL_FOLDER="${CNODE_HOME}/priv/pool"                  # Root folder for Pools
                                                         # Each wallet and pool has a friendly name and subfolder containing all related keys, certificates, ...
-POOL_NAME="LKBH"                                           # Set the pool's name to run node as a core node (the name, NOT the ticker, ie folder name)
+POOL_NAME="REIT"                                           # Set the pool's name to run node as a core node (the name, NOT the ticker, ie folder name)
 
 #WALLET_PAY_VK_FILENAME="payment.vkey"                  # Standardized names for all wallet related files
 #WALLET_PAY_SK_FILENAME="payment.skey"
@@ -76,14 +76,12 @@ POOL_NAME="LKBH"                                           # Set the pool's name
 #ENABLE_KOIOS=Y                                         # (Y|N) Enable KOIOS API. If disabled, local node queries will be used instead with increased system resource requirements (default Y)
 #KOIOS_API="https://api.koios.rest/api/v0/"             # Koios API for blockchain queries instead of local cli lookup.
 #G_ACCOUNT="cardano-community"             # Override default github repository if you forked project
+#USESYSVARS="N"                                         # Whether to use environment variable from shell session for TCONFIG_HOME
+#POOL_HW_COLDKEY_SK_FILENAME="cold.hwsfile"
 
 ######################################
 # Do NOT modify code below           #
 ######################################
-
-# Initialise/Set offline mode prior to calling functions
-OFFLINE_MODE='N'
-[[ $1 = "offline" ]] && OFFLINE_MODE='Y'
 
 # Description : Check if provided file exists
 #             : $1 = File (with path) to check
@@ -163,9 +161,6 @@ checkUpdate() {
   [[ -n $5 ]] && URL="${URL_RAW}/scripts/$5" || URL="${URL_RAW}/scripts/cnode-helper-scripts"
   URL_DOCS="${URL_RAW}/docs/Scripts"
   if curl -s -f -m ${CURL_TIMEOUT} -o "${dname}/${fname}".tmp "${URL}/${fname}" 2>/dev/null; then
-
-    # replace default CNODE with custom name if needed
-    [[ ${CNODE_VNAME} != cnode ]] && sed -e "s@/opt/cardano/[c]node@/opt/cardano/${CNODE_VNAME}@g" -e "s@[C]NODE_HOME@${CNODE_VNAME_UPPERCASE}_HOME@g" -i "${dname}/${fname}".tmp
 
     # make sure script exist, else just rename
     [[ ! -f "${dname}/${fname}" ]] && mv -f "${dname}/${fname}".tmp "${dname}/${fname}" && chmod +x "${dname}/${fname}" && return 0
@@ -282,10 +277,10 @@ joinArray() {
 # Description : Generate asset id according to CIP-14 standard
 #               https://github.com/cardano-foundation/CIPs/pull/64
 #             : $1 = hex-encoded policy ID
-#             : $2 = ASCII formatted asset name
+#             : $2 = hex-encoded asset name
 getAssetIDBech32() {
   { ! cmdAvailable "bech32" || ! cmdAvailable "b2sum"; } && return 1
-  printf "$(echo -n $1 | sed 's/../\\x&/g')%s" "$2" | b2sum -l 160 -b | cut -d' ' -f 1 | bech32 asset
+  printf "$(echo -n $1$2 | sed 's/../\\x&/g')" | b2sum -l 160 -b | cut -d' ' -f 1 | bech32 asset
 }
 
 # Description : Convert a normal 1 byte ASCII string to hex (alnum chars)
@@ -294,7 +289,7 @@ asciiToHex() {
   local ascwrd=$1
   [[ -z ${ascwrd} ]] && return
   for ((i=0;i<${#ascwrd};i++)); do
-    printf %02x \'${ascwrd:$i:1}
+    printf %02x \'"${ascwrd:$i:1}"
   done
 }
 
@@ -306,7 +301,7 @@ hexToAscii() {
   [[ -z ${hexstr} ]] && return
   (( hexcnt % 2 != 0 )) && return
   for ((i=0;i<${#hexstr};i=i+2)); do
-    printf "\x${hexstr:$i:2}"
+    [[ ${hexstr:$i:2} = "00" ]] && printf "\x20" || printf "\x${hexstr:$i:2}" # 00 = NUL char, special case handling
   done
 }
 
@@ -720,8 +715,6 @@ getEraIdentifier() {
   return 0
 }
 
-[[ ${0} != '-bash' ]] && PARENT=$(dirname $0) || PARENT="$(pwd)" # If sourcing at terminal, $0 would be "-bash" , which is invalid. Thus, fallback to present working directory
-
 telegramSend() {
   if [[ -z "${TG_BOT_TOKEN}" ]] || [[ -z "${TG_CHAT_ID}" ]]; then
     echo "Warn: to use the telegramSend function you must first set the bot and chat id in the env file"
@@ -732,6 +725,8 @@ telegramSend() {
 }
 
 set_default_vars() {
+
+  [[ "${USESYSVARS}" != "Y" ]] && unset TCONFIG_HOME
   [[ $(basename $0 2>/dev/null) = "cnode.sh" ]] && OFFLINE_MODE='Y' # for backwards compatibility
   [[ $(basename $0 2>/dev/null) = "topologyUpdater.sh" ]] && OFFLINE_MODE='Y' # for backwards compatibility
 
@@ -746,7 +741,7 @@ set_default_vars() {
      date () { gdate "$@"; }
   fi
   [[ -z ${CURL_TIMEOUT} ]] && CURL_TIMEOUT=10
-  [[ -z "${TCONFIG_HOME}" ]] && TCONFIG_HOME=/opt/cardano/tconfig
+  [[ -z "${TCONFIG_HOME}" ]] && TCONFIG_HOME="$(readlink -f ${PARENT}/..)"
   CNODE_NAME="$(basename ${TCONFIG_HOME})"
   CNODE_VNAME=$(tr '[:upper:]' '[:lower:]' <<< ${CNODE_NAME//_HOME/})
   CNODE_VNAME_UPPERCASE=$(tr '[:lower:]' '[:upper:]' <<< ${CNODE_VNAME})
@@ -783,6 +778,7 @@ set_default_vars() {
   [[ -z ${POOL_HOTKEY_SK_FILENAME} ]] && POOL_HOTKEY_SK_FILENAME="hot.skey"
   [[ -z ${POOL_COLDKEY_VK_FILENAME} ]] && POOL_COLDKEY_VK_FILENAME="cold.vkey"
   [[ -z ${POOL_COLDKEY_SK_FILENAME} ]] && POOL_COLDKEY_SK_FILENAME="cold.skey"
+  [[ -z ${POOL_HW_COLDKEY_SK_FILENAME} ]] && POOL_HW_COLDKEY_SK_FILENAME="cold.hwsfile"
   [[ -z ${POOL_OPCERT_COUNTER_FILENAME} ]] && POOL_OPCERT_COUNTER_FILENAME="cold.counter"
   [[ -z ${POOL_OPCERT_FILENAME} ]] && POOL_OPCERT_FILENAME="op.cert"
   [[ -z ${POOL_VRF_VK_FILENAME} ]] && POOL_VRF_VK_FILENAME="vrf.vkey"
@@ -812,12 +808,17 @@ set_default_vars() {
   NC='\e[0m'
 }
 
+[[ ${0} != '-bash' ]] && PARENT=$(dirname $0) || PARENT="$(pwd)" # If sourcing at terminal, $0 would be "-bash" , which is invalid. Thus, fallback to present working directory
+# Initialise/Set offline mode prior to calling functions
+OFFLINE_MODE='N'
+[[ $1 = "offline" ]] && OFFLINE_MODE='Y'
+
 set_default_vars
 
 [[ -z "${CCLI}" ]] && CCLI=$(command -v cardano-cli)
 if [[ -z "${CCLI}" ]]; then
-  if [[ -f "${HOME}/.cabal/bin/cardano-cli" ]]; then
-    export PATH="${HOME}/.cabal/bin":$PATH
+  if [[ -f "${HOME}/.local/bin/cardano-cli" ]]; then
+    export PATH="${HOME}/.local/bin":$PATH
     CCLI=$(command -v cardano-cli)
   else
     echo "You do not have a cardano-cli binary available in \$PATH."
@@ -830,17 +831,17 @@ if [[ -z "${CNODEBIN}" ]]; then
   if [[ -f "$(dirname ${CCLI})"/cardano-node ]]; then
     CCLIPARENT="$(dirname ${CCLI})" && export PATH="${CCLIPARENT}":$PATH
     CNODEBIN="$(dirname ${CCLI})"/cardano-node
-  elif [[ -f "${HOME}/.cabal/bin/cardano-node" ]]; then
-    export PATH="${HOME}/.cabal/bin":$PATH
+  elif [[ -f "${HOME}/.local/bin/cardano-node" ]]; then
+    export PATH="${HOME}/.local/bin":$PATH
     CNODEBIN=$(command -v cardano-node)
-  elif [[ ${OFFLINE_MODE} = "Y" ]]; then
+  elif [[ ${OFFLINE_MODE} = "N" ]]; then
     echo "You do not have a cardano-node binary available in \$PATH."
     return 1
   fi
 fi
 
 if [[ -z "${CNCLI}" ]]; then
-  CNCLI=$(command -v cncli) || CNCLI="${HOME}/.cargo/bin/cncli"
+  CNCLI=$(command -v cncli) || CNCLI="${HOME}/.local/bin/cncli"
 fi
 
 [[ -f /usr/local/lib/libsodium.so ]] && export LD_LIBRARY_PATH=/usr/local/lib:"${LD_LIBRARY_PATH}" && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:"${PKG_CONFIG_PATH}"
@@ -875,12 +876,12 @@ if command -v "ss" &>/dev/null; then
 elif command -v "lsof" &>/dev/null; then
   use_lsof='Y'
 else
-  echo -e "'ss' and fallback 'lsof' commands are missing, please install using latest prereqs.sh script or with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
+  echo -e "'ss' and fallback 'lsof' commands are missing, please install using latest guild-deploy.sh script or with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
   return 1
 fi
 
 if ! command -v "jq" &>/dev/null; then
-  echo -e "'jq' command is missing, please install using latest prereqs.sh script of with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
+  echo -e "'jq' command is missing, please install using latest guild-deploy.sh script of with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
   return 1
 fi
 
@@ -978,8 +979,8 @@ if [[ -n "${CNODE_PID}" ]]; then
 fi
 
 node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "1.35.2" "${node_version}"; then
-  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.35.2 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
+if ! versionCheck "1.35.5" "${node_version}"; then
+  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.35.5 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
   return 1
 fi
 
@@ -1019,10 +1020,6 @@ case ${NWMAGIC} in
     NETWORK_NAME="Preview"
     SHELLEY_TRANS_EPOCH=0
     [[ -z ${KOIOS_API} ]] && KOIOS_API="https://preview.koios.rest/api/v0" ;;
-  1097911063) # To be retired soon
-    NETWORK_NAME="Testnet"
-    SHELLEY_TRANS_EPOCH=74
-    [[ -z ${KOIOS_API} ]] && KOIOS_API="https://testnet.koios.rest/api/v0" ;;
   *) 
     NETWORK_NAME="Custom"
     [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=0
